/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetable_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import timetable_management_system.ParallelTable;
import timetable_management_system.Parallels;
import timetable_management_system.SessionT;

/**
 *
 * @author NISHADI
 */
public class Parallel extends javax.swing.JFrame {
  
    
    public Parallel() {
        initComponents();
        
        
        //center form
    this.setLocationRelativeTo(null);
       

    }

      public Connection getConnection(){
      Connection con;
        try{
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3307/itpmnew","root","");
            return con;
        }catch(Exception e){
            e.printStackTrace();
            return null;
            
        }
        
    }
    
      
           public ArrayList<Parallels> getParallelsList()
    {
        ArrayList<Parallels> parallelsList = new ArrayList<>();
        Connection connection = getConnection();
        String query = "SELECT * FROM `parallel`";
        Statement st;
        ResultSet rs;
        
        try{
            st = connection.createStatement();
            rs = st.executeQuery(query);
            Parallels parallels;
            while(rs.next()){
                parallels = new Parallels(rs.getInt("paralleID"),rs.getString("parYear"),rs.getString("parSemester"),rs.getString("parSpecial"),rs.getString("parTag"),rs.getString("parCode1"),rs.getString("parCode2"),rs.getString("parCode3"),rs.getString("parCode4"),rs.getString("parSession1"),rs.getString("parSession2"),rs.getString("parSession3"),rs.getString("parSession4"));
                parallelsList.add(parallels);
                
            }
               
        }catch(Exception e){
            e.printStackTrace();
        }
        return parallelsList;
    }      
     
           

                     //Exequte The Sql Query
   public void executeSQlQuery(String query, String message){
        Connection con = getConnection();
        Statement st;
        try{
            st = con.createStatement();
            if((st.executeUpdate(query)) == 1)
            {
               
                JOptionPane.showMessageDialog(null, "Data"+message+" Succefully");
            }else{
                JOptionPane.showMessageDialog(null, "Data Not"+message);
            }
        
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton_prBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox_pYear = new javax.swing.JComboBox<>();
        jComboBox1_pSemeter = new javax.swing.JComboBox<>();
        jComboBox_Session3 = new javax.swing.JComboBox<>();
        jComboBox_TypeOfSubject = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_pSubjectCode1 = new javax.swing.JComboBox<>();
        jComboBox_pSubjectCode2 = new javax.swing.JComboBox<>();
        jComboBox_pSubjectCode3 = new javax.swing.JComboBox<>();
        jComboBox_pSubjectCode4 = new javax.swing.JComboBox<>();
        jComboBox_Session1 = new javax.swing.JComboBox<>();
        jComboBox_Session2 = new javax.swing.JComboBox<>();
        jComboBox_session3 = new javax.swing.JComboBox<>();
        jComboBox_Session4 = new javax.swing.JComboBox<>();
        jButton_pGetData = new javax.swing.JButton();
        jButton_pAdd = new javax.swing.JButton();
        jButton_pView = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1_home = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel_logout = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2Minimize = new javax.swing.JLabel();
        jLabel1close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(42, 62, 80));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add Parallel Sessions");

        jButton_prBack.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_prBack.setText("BACK");
        jButton_prBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_prBackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Academic Year:-");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Academic Semester:-");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Specalization:-");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tag:-");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Subject Code:-");

        jComboBox_pYear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_pYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_pYearActionPerformed(evt);
            }
        });

        jComboBox1_pSemeter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jComboBox_Session3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_Session3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Session3ActionPerformed(evt);
            }
        });

        jComboBox_TypeOfSubject.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Session:-");

        jComboBox_pSubjectCode1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_pSubjectCode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_pSubjectCode1ActionPerformed(evt);
            }
        });

        jComboBox_pSubjectCode2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jComboBox_pSubjectCode3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_pSubjectCode3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_pSubjectCode3ActionPerformed(evt);
            }
        });

        jComboBox_pSubjectCode4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jComboBox_Session1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jComboBox_Session2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jComboBox_session3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox_session3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_session3ActionPerformed(evt);
            }
        });

        jComboBox_Session4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton_pGetData.setBackground(new java.awt.Color(236, 236, 236));
        jButton_pGetData.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_pGetData.setText("GET DATA");
        jButton_pGetData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_pGetDataActionPerformed(evt);
            }
        });

        jButton_pAdd.setBackground(new java.awt.Color(1, 152, 117));
        jButton_pAdd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_pAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButton_pAdd.setText("ADD");
        jButton_pAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_pAddActionPerformed(evt);
            }
        });

        jButton_pView.setBackground(new java.awt.Color(207, 0, 15));
        jButton_pView.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_pView.setForeground(new java.awt.Color(255, 255, 255));
        jButton_pView.setText("VIEW");
        jButton_pView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_pViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(339, 339, 339))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBox_pSubjectCode3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox_pSubjectCode2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox_pSubjectCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox_pSubjectCode4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26))
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jComboBox_session3, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBox_Session1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBox_Session2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBox_Session4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox_TypeOfSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox1_pSemeter, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(101, 101, 101)
                                .addComponent(jComboBox_pYear, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox_Session3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(229, 229, 229))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton_prBack)
                        .addGap(79, 79, 79)
                        .addComponent(jButton_pGetData)
                        .addGap(71, 71, 71)
                        .addComponent(jButton_pAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jButton_pView, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox_pYear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1_pSemeter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox_Session3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_TypeOfSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_pSubjectCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_pSubjectCode2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_pSubjectCode3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_pSubjectCode4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox_Session1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_Session2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_session3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_Session4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_prBack, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_pGetData, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_pAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_pView, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        jPanel1.setBackground(new java.awt.Color(236, 236, 236));

        jLabel1_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home2.jpg"))); // NOI18N
        jLabel1_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_homeMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel10.setText("Time Table Management System");

        jLabel_logout.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_logout.setText("Logout");
        jLabel_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_logoutMouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.jpg"))); // NOI18N

        jLabel2Minimize.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2Minimize.setText("-");
        jLabel2Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MinimizeMouseClicked(evt);
            }
        });

        jLabel1close.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1close.setText("X");
        jLabel1close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1_home)
                .addGap(242, 242, 242)
                .addComponent(jLabel10)
                .addGap(79, 79, 79)
                .addComponent(jLabel_logout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jLabel2Minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1close, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1close)
                                .addComponent(jLabel2Minimize))
                            .addGap(14, 14, 14))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel_logout)
                                .addComponent(jLabel10))))
                    .addComponent(jLabel1_home))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_prBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_prBackActionPerformed
        // TODO add your handling code here:
        SessionT sess = new SessionT();
        sess.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_prBackActionPerformed

    private void jButton_pAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_pAddActionPerformed
        // TODO add your handling code here:
       //  String query = "INSERT INTO `student`(`sID`, `sYear`, `sSemester`, `sProgramme`, `sMaiGroupNumber`, `sSubGroupNumber`, `sMainGroupId`, `sSubGroupId`) VALUES ('"+sId.getText()+"','"+sYear.getSelectedItem()+"','"+sSemester.getSelectedItem()+"','"+sProgramme.getText()+"','"+sMainGroupNumber.getText()+"','"+sSubGroupNumber.getText()+"','"+sMainGroupId.getText()+"','"+sSubGroupId.getText()+"')";
      
        String query = "INSERT INTO `parallel`(`parYear`, `parSemester`, `parSpecial`, `parTag`, `parCode1`, `parCode2`, `parCode3`, `parCode4`, `parSession1`, `parSession2`, `parSession3`, `parSession4`) VALUES ('"+jComboBox_pYear.getSelectedItem()+"','"+jComboBox1_pSemeter.getSelectedItem()+"','"+jComboBox_Session3.getSelectedItem()+"','"+jComboBox_TypeOfSubject.getSelectedItem()+"','"+jComboBox_pSubjectCode1.getSelectedItem()+"','"+jComboBox_pSubjectCode2.getSelectedItem()+"','"+jComboBox_pSubjectCode3.getSelectedItem()+"','"+jComboBox_pSubjectCode4.getSelectedItem()+"','"+jComboBox_Session1.getSelectedItem()+"','"+jComboBox_Session2.getSelectedItem()+"','"+jComboBox_session3.getSelectedItem()+"','"+jComboBox_Session4.getSelectedItem()+"')";
        executeSQlQuery(query, " Inserted");
        
        
//INSERT INTO `parallel`(`paralleID`, `parYear`, `parSemester`, `parSubjectType`, `parSubject1`, `parSubject2`, `parSubject3`, `parSubject4`, `parCode1`, `parCode2`, `parCode3`, `parCode4`) VALUES ([value-1],[value-2],[value-3],[value-4],[value-5],[value-6],[value-7],[value-8],[value-9],[value-10],[value-11],[value-12])
    }//GEN-LAST:event_jButton_pAddActionPerformed

    private void jButton_pViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_pViewActionPerformed
        // TODO add your handling code here:
         ParallelTable par = new ParallelTable();
        par.setVisible(true);
        this.dispose();
        
       /* ParallelTable  jTable_parallel = new ParallelTable();
        jTable_parallel.setVisible(true);
        this.dispose();
        */
        
      /*  ParallelTable.AddRowToJTable(new Object[]{
                                                         jTextField_pYear.getText(),
                                                         jTextField_pSemeter.getText(),
                                                         jTextField_pTypeOfSubject.getText(),
                                                         jTextField_pSubject1.getText(),
                                                         jTextField_pSubject2.getText(),
                                                         jTextField_pSubject3.getText(),
                                                         jTextField_pSubject4.getText(),
                                                         jTextField_pSubjectCode1.getText(),
                                                         jTextField_pSubjectCode2.getText(),
                                                         jTextField_pSubjectCode3.getText(),
                                                         jTextField_pSubjectCode4.getText(),
                               });*/
      
     /* ParallelTable.AddRowToJTable(new Object[]{
                
                                                         jComboBox_pYear.getSelectedItem(),
                                                         jComboBox1_pSemeter.getSelectedItem(),
                                                         jComboBox_Special.getSelectedItem(),
                                                         jComboBox_TypeOfSubject.getSelectedItem(),
                                                         jComboBox_pSubjectCode1.getSelectedItem(),
                                                         jComboBox_pSubjectCode2.getSelectedItem(),
                                                         jComboBox_pSubjectCode3.getSelectedItem(),
                                                         jComboBox_pSubjectCode4.getSelectedItem(),
      });*/
    }//GEN-LAST:event_jButton_pViewActionPerformed

    private void jComboBox_pYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_pYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_pYearActionPerformed

    private void jButton_pGetDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_pGetDataActionPerformed
        // TODO add your handling code here:
        try{
            Connection con = getConnection();
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("SELECT distinct sYear FROM `student`");
            
            
            while(rs.next()){
                String pYe = rs.getString("sYear");
                jComboBox_pYear.addItem(pYe);
                
            }
           
            
        }catch(Exception e){
            
        } 
        
        
        try{
            Connection con = getConnection();
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("SELECT distinct sSemester FROM `student`");
            
            
            while(rs.next()){
                String pSem = rs.getString("sSemester");
                jComboBox1_pSemeter.addItem(pSem);
                
            }
           
            
        }catch(Exception e){
            
        } 
        
        try{
            Connection con = getConnection();
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("SELECT distinct sProgramme FROM `student`");
            
            
            while(rs.next()){
                String pProgramme = rs.getString("sProgramme");
                jComboBox_Session3.addItem(pProgramme);
                
            }
           
            
        }catch(Exception e){
            
        } 
        

        
         try{
            Connection con = getConnection();
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("SELECT distinct session_ID FROM `session`");
            
           while(rs.next()){
                String sess = rs.getString("session_ID");
                jComboBox_Session1.addItem(sess);
                jComboBox_Session2.addItem(sess);
                jComboBox_session3.addItem(sess);
                jComboBox_Session4.addItem(sess);
            }
            
        }catch(Exception e){
            
        } 
         
         
         
        try{
            Connection con = getConnection();
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery("SELECT distinct full_grpID FROM `session`");
            
           while(rs.next()){
                String pGroupID = rs.getString("full_grpID");
                jComboBox_pSubjectCode1.addItem(pGroupID);
                jComboBox_pSubjectCode2.addItem(pGroupID);
                jComboBox_pSubjectCode3.addItem(pGroupID);
                jComboBox_pSubjectCode4.addItem(pGroupID);
            }
            
        }catch(Exception e){
            
        } 
        
    }//GEN-LAST:event_jButton_pGetDataActionPerformed

    private void jComboBox_pSubjectCode3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_pSubjectCode3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_pSubjectCode3ActionPerformed

    private void jComboBox_pSubjectCode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_pSubjectCode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_pSubjectCode1ActionPerformed

    private void jComboBox_session3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_session3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_session3ActionPerformed

    private void jComboBox_Session3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Session3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_Session3ActionPerformed

    private void jLabel1_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_homeMouseClicked

        Admin_Home aho = new Admin_Home();
        aho.setVisible(true);
        aho.pack();
        aho.setLocationRelativeTo(null);
        aho.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel1_homeMouseClicked

    private void jLabel_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_logoutMouseClicked
        Admin_Login adlogin = new Admin_Login();
        adlogin.setVisible(true);
        adlogin.pack();
        adlogin.setLocationRelativeTo(null);
        adlogin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();//when the admin page is loading, add lecturer page is removed
    }//GEN-LAST:event_jLabel_logoutMouseClicked

    private void jLabel2MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel2MinimizeMouseClicked

    private void jLabel1closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1closeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parallel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parallel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parallel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parallel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parallel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_pAdd;
    private javax.swing.JButton jButton_pGetData;
    private javax.swing.JButton jButton_pView;
    private javax.swing.JButton jButton_prBack;
    private javax.swing.JComboBox<String> jComboBox1_pSemeter;
    private javax.swing.JComboBox<String> jComboBox_Session1;
    private javax.swing.JComboBox<String> jComboBox_Session2;
    private javax.swing.JComboBox<String> jComboBox_Session3;
    private javax.swing.JComboBox<String> jComboBox_Session4;
    private javax.swing.JComboBox<String> jComboBox_TypeOfSubject;
    private javax.swing.JComboBox<String> jComboBox_pSubjectCode1;
    private javax.swing.JComboBox<String> jComboBox_pSubjectCode2;
    private javax.swing.JComboBox<String> jComboBox_pSubjectCode3;
    private javax.swing.JComboBox<String> jComboBox_pSubjectCode4;
    private javax.swing.JComboBox<String> jComboBox_pYear;
    private javax.swing.JComboBox<String> jComboBox_session3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel1_home;
    private javax.swing.JLabel jLabel1close;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2Minimize;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_logout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
