
package timetable_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author NISHADI
 */
public class SessionT extends javax.swing.JFrame {

    
    public SessionT() {
        initComponents();
       // findSessions();
       
       
       
           //center form
    this.setLocationRelativeTo(null);
    }
    
    
   /* public Connection getConnection(){
      Connection con;
        try{
            
            con = DriverManager.getConnection("jdbc:mysql://localhost:3307/itpmnew","root","");
            return con;
        }catch(Exception e){
            e.printStackTrace();
            return null;
            
        }
        
    }
    
   public ArrayList<Session> ListSessions(String ValToSearch){
        ArrayList<Session> sessionsList = new ArrayList<Session>();
        
        
        Statement st;
        ResultSet rs;
        
        try{
            
            //Connection con = getConnection();
            Connection con = getConnection();
            st = con.createStatement();
            String searchQuery = "SELECT * FROM `session` WHERE CONCAT(`sessionId`,`se_lecture1`,`se_lecture2`,`se_subjectCode`,`se_subjectName`,`se_groupId`,`se_tag`)LIKE'%"+ValToSearch+"%'";
            rs = st.executeQuery(searchQuery);
            
            Session session;
            
            while(rs.next())
            {
                session = new Session(
                                        rs.getInt("sessionId"),
                                        rs.getString("se_lecture1"),
                                        rs.getString("se_lecture2"),
                                        rs.getString("se_subjectCode"),
                                        rs.getString("se_subjectName"),
                                        rs.getString("se_groupId"),
                                        rs.getString("se_tag")
                
                                       );
                sessionsList.add(session);
            }
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
        return sessionsList;
    }
    
    
    public void findSessions()
    {
        ArrayList<Session> sessions = ListSessions(jText_Search.getText());
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"sessionId","se_lecture1","se_lecture2","se_subjectCode","se_subjectName","se_groupId","se_tag"});
        Object[] row = new Object[7];
        
        for(int i = 0; i < sessions.size(); i++){
            
            row[0] = sessions.get(i).getSessionId();
            row[1] = sessions.get(i).getSe_lecture1();
            row[2] = sessions.get(i).getSe_lecture2();
            row[3] = sessions.get(i).getSe_subjectCode();
            row[4] = sessions.get(i).getSe_subjectName();
            row[5] = sessions.get(i).getSe_groupId();
            row[6] = sessions.get(i).getSe_tag();
            model.addRow(row);
            
        }
        
        jTable_Sessions.setModel(model);
            
      }

    private void initComponents() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static class jTable_Sessions {

        public jTable_Sessions() {
        }
    }
                
                
        
        
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1_home = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel_logout = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2Minimize = new javax.swing.JLabel();
        jLabel1close = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton_show_table_details = new javax.swing.JButton();
        jButton_Consecutive = new javax.swing.JButton();
        jButton_Parallel = new javax.swing.JButton();
        jButton_nonOverlapping = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Sessions = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jText_Search = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(236, 236, 236));

        jLabel1_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home2.jpg"))); // NOI18N
        jLabel1_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1_homeMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel10.setText("Time Table Management System");

        jLabel_logout.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel_logout.setText("Logout");
        jLabel_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_logoutMouseClicked(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user.jpg"))); // NOI18N

        jLabel2Minimize.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2Minimize.setText("-");
        jLabel2Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MinimizeMouseClicked(evt);
            }
        });

        jLabel1close.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1close.setText("X");
        jLabel1close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1_home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(91, 91, 91)
                .addComponent(jLabel_logout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(48, 48, 48)
                .addComponent(jLabel2Minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1close, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel_logout))
                            .addComponent(jLabel11)
                            .addComponent(jLabel1_home)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2Minimize)
                            .addComponent(jLabel1close))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jButton_show_table_details.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_show_table_details.setText("Show Table Details");
        jButton_show_table_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_show_table_detailsActionPerformed(evt);
            }
        });

        jButton_Consecutive.setBackground(new java.awt.Color(3, 166, 120));
        jButton_Consecutive.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_Consecutive.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Consecutive.setText("Add Consecutive Sessions");
        jButton_Consecutive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConsecutiveActionPerformed(evt);
            }
        });

        jButton_Parallel.setBackground(new java.awt.Color(63, 195, 128));
        jButton_Parallel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_Parallel.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Parallel.setText("Add Parallel Sessions");
        jButton_Parallel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ParallelActionPerformed(evt);
            }
        });

        jButton_nonOverlapping.setBackground(new java.awt.Color(1, 152, 117));
        jButton_nonOverlapping.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_nonOverlapping.setForeground(new java.awt.Color(255, 255, 255));
        jButton_nonOverlapping.setText("Add Non Overlapping Sessions");
        jButton_nonOverlapping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nonOverlappingActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sessions");

        jTable_Sessions.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTable_Sessions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Lecture1", "Lecture2", "Module Code", "Module Name", "Student Count", "Tag", "Duration", "Main Group", "Sub Group", "GroupID"
            }
        ));
        jScrollPane1.setViewportView(jTable_Sessions);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search :-");

        jText_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jText_SearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_show_table_details, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Parallel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_nonOverlapping, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Consecutive, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(132, 132, 132))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jText_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jText_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Consecutive, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_show_table_details, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Parallel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_nonOverlapping, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_show_table_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_show_table_detailsActionPerformed
        // TODO add your handling code here:
        
        try{
           Connection con;
           con = DriverManager.getConnection("jdbc:mysql://localhost:3306/itpmnew","root","");
                   
                    
            Statement st = con.createStatement();
            
           //mySql query
           String sql = "SELECT * FROM `session`";
           ResultSet rs = st.executeQuery(sql);
           
           while(rs.next()){
               //data will be added until finish session table data
               String session_ID = String.valueOf(rs.getInt("session_ID"));
               String lec1 = rs.getString("lec1");
               String lec2 = rs.getString("lec2");
               String sub_code = rs.getString("sub_code");
               String sub_name = rs.getString("sub_name");
               String stu_count = String.valueOf(rs.getInt("stu_count"));
               String tag = rs.getString("tag");
               String duration = String.valueOf(rs.getInt("duration"));
               String maingroup = rs.getString("Maingroup");
               String subgroup = rs.getString("Subgroup");
               String full_grpID = rs.getString("full_grpID");
              
               //String array for data into jTable
               String session[] = {session_ID,lec1,lec2,sub_code,sub_name,stu_count,tag,duration,maingroup,subgroup,full_grpID};
               
               //DefaultTableModel tblModel = (DefaultTableModel)jTable_SessionsT.getModel();
               DefaultTableModel tblModel = (DefaultTableModel)jTable_Sessions.getModel();
               //add string array data in to jTable
               tblModel.addRow(session);
                       }
           con.close();
       }catch(Exception e){
           e.printStackTrace();
            
            
        
    }                                        
    }//GEN-LAST:event_jButton_show_table_detailsActionPerformed

    private void jText_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jText_SearchKeyReleased
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel)jTable_Sessions.getModel();
        String search = jText_Search.getText();
        //TableRowSorter<DefaultTableMoel> tr = new TableRowSorter<DefaultTableModel>(model);
         
         TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
       jTable_Sessions.setRowSorter(tr);
       tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_jText_SearchKeyReleased

    private void jButton_ConsecutiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConsecutiveActionPerformed
        // TODO add your handling code here:
            Consecutive conse = new Consecutive();
            conse.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton_ConsecutiveActionPerformed

    private void jButton_ParallelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ParallelActionPerformed
        // TODO add your handling code here:
            Parallel par = new Parallel();
            par.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton_ParallelActionPerformed

    private void jButton_nonOverlappingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nonOverlappingActionPerformed
        // TODO add your handling code here:
         Overlapping over = new Overlapping();
         over.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButton_nonOverlappingActionPerformed

    private void jLabel1_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1_homeMouseClicked

        Admin_Home aho = new Admin_Home();
        aho.setVisible(true);
        aho.pack();
        aho.setLocationRelativeTo(null);
        aho.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel1_homeMouseClicked

    private void jLabel_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_logoutMouseClicked
        Admin_Login adlogin = new Admin_Login();
        adlogin.setVisible(true);
        adlogin.pack();
        adlogin.setLocationRelativeTo(null);
        adlogin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();//when the admin page is loading, add lecturer page is removed
    }//GEN-LAST:event_jLabel_logoutMouseClicked

    private void jLabel2MinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MinimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel2MinimizeMouseClicked

    private void jLabel1closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1closeMouseClicked

    
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SessionT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Consecutive;
    private javax.swing.JButton jButton_Parallel;
    private javax.swing.JButton jButton_nonOverlapping;
    private javax.swing.JButton jButton_show_table_details;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel1_home;
    private javax.swing.JLabel jLabel1close;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2Minimize;
    private javax.swing.JLabel jLabel_logout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Sessions;
    private javax.swing.JTextField jText_Search;
    // End of variables declaration//GEN-END:variables
}
